"""create_initial_phishguard_tables

Revision ID: d3b98392601e
Revises: 
Create Date: 2026-08-25 21:43:26.316385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3b98392601e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('version', sa.String(length=100), nullable=False),
    sa.Column('algorithm', sa.String(length=255), nullable=False),
    sa.Column('metrics_json', sa.JSON(), nullable=False),
    sa.Column('dataset_description', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version'),
    sa.UniqueConstraint('version', name='uq_model_versions_version')
    )
    op.create_index(op.f('ix_model_versions_is_active'), 'model_versions', ['is_active'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("role IN ('user', 'admin')", name='ck_users_role'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='uq_users_email')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('scans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('classification', sa.String(length=50), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('legitimate_probability', sa.Float(), nullable=False),
    sa.Column('phishing_probability', sa.Float(), nullable=False),
    sa.Column('model_version', sa.String(length=100), nullable=False),
    sa.Column('processing_time_ms', sa.Integer(), nullable=False),
    sa.Column('url_count', sa.Integer(), nullable=False),
    sa.Column('indicator_count', sa.Integer(), nullable=False),
    sa.Column('high_severity_count', sa.Integer(), nullable=False),
    sa.Column('sender_domain', sa.String(length=255), nullable=True),
    sa.Column('recipient_domain', sa.String(length=255), nullable=True),
    sa.Column('subject_preview', sa.String(length=255), nullable=True),
    sa.Column('indicators_json', sa.JSON(), nullable=False),
    sa.Column('urls_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("classification IN ('safe', 'suspicious', 'phishing')", name='ck_scans_classification'),
    sa.CheckConstraint('confidence >= 0.0 AND confidence <= 1.0', name='ck_scans_confidence'),
    sa.CheckConstraint('high_severity_count >= 0 AND high_severity_count <= indicator_count', name='ck_scans_high_severity_count'),
    sa.CheckConstraint('indicator_count >= 0', name='ck_scans_indicator_count'),
    sa.CheckConstraint('legitimate_probability >= 0.0 AND legitimate_probability <= 1.0', name='ck_scans_legitimate_probability'),
    sa.CheckConstraint('phishing_probability >= 0.0 AND phishing_probability <= 1.0', name='ck_scans_phishing_probability'),
    sa.CheckConstraint('processing_time_ms >= 0', name='ck_scans_processing_time'),
    sa.CheckConstraint('risk_score >= 0 AND risk_score <= 100', name='ck_scans_risk_score'),
    sa.CheckConstraint('url_count >= 0', name='ck_scans_url_count'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scans_created_at'), 'scans', ['created_at'], unique=False)
    op.create_index(op.f('ix_scans_user_id'), 'scans', ['user_id'], unique=False)
    op.create_table('feedbacks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scan_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('actual_label', sa.String(length=50), nullable=False),
    sa.Column('is_helpful', sa.Boolean(), nullable=False),
    sa.Column('comment', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("actual_label IN ('safe', 'suspicious', 'phishing')", name='ck_feedbacks_actual_label'),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'scan_id', name='uq_feedbacks_user_scan')
    )
    op.create_index(op.f('ix_feedbacks_scan_id'), 'feedbacks', ['scan_id'], unique=False)
    op.create_index(op.f('ix_feedbacks_user_id'), 'feedbacks', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feedbacks_user_id'), table_name='feedbacks')
    op.drop_index(op.f('ix_feedbacks_scan_id'), table_name='feedbacks')
    op.drop_table('feedbacks')
    op.drop_index(op.f('ix_scans_user_id'), table_name='scans')
    op.drop_index(op.f('ix_scans_created_at'), table_name='scans')
    op.drop_table('scans')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_model_versions_is_active'), table_name='model_versions')
    op.drop_table('model_versions')
    # ### end Alembic commands ###
